### PR TITLE
Added token_to_token auth

### PR DESCRIPTION
**Pull request by zw5**
This pull request makes it possible to use the grant type `token_to_token` which allows for creating a new token without expiring the old one, would be really useful for having 2 bots logged in to the same account and it could possibly even help with further development on sharding systems and such.

### CODE REVIEW

**Comment by Terbau** [comment]
Before merging I would need you to add the auth to the documentation in api.rst.

**Comment by zw5** [comment]
Alright, i will make another commit with the added documentation.

**Comment by zw5** [comment]
Done, can you review again, @Terbau ?

**Comment by Terbau** [comment]
Thanks. I'll review it once im home and then merge it.

**Comment by Terbau** [comment]
After testing I have decided not to merge because the ios client basic token is not allowed to use `token_to_token`. 

Not really important since it won't work either way but you forgot to change `refresh_token` to `access_token`.

**Comment by zw5** [comment]
I will make improvements to this pull request and open another iteration of it later.

**Pull request closed without merging**
